version: "3.9"

services:
  redis:
    image: redis:alpine
    expose:
      - '6379'
    networks:
      - djangonetwork

  celery:
      restart: always
      build:
        context: .
      command: celery -A support_site worker -l info
      volumes:
        - .:/code
      depends_on:
        - db
        - redis
        - web
      networks:
        - djangonetwork

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - djangonetwork
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    networks:
      - djangonetwork
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
networks:
      djangonetwork:
          driver: bridge

